# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
  exporters:
    otlp:
      endpoint: 18.61.77.172:4217
      tls:
        insecure: true
    otlphttp:
      endpoint: http://18.61.77.172:4218
      tls:
        insecure: true

  service:
    pipelines:
      traces:
        exporters: [spanmetrics, otlp]
      metrics:
        exporters: [otlphttp]
      logs:
        exporters: [otlphttp]
