# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
exporters:
  # HTTP setup
  otlphttp/hdx:
    endpoint: 'http://18.61.77.172:4318'
    tls:
      insecure: true
 
  # gRPC setup (alternative)
  otlp/hdx:
    endpoint: '18.61.77.172:4317'
    tls:
      insecure: true
 
service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlphttp/hdx]
    metrics:
      exporters: [otlphttp/hdx]
    logs:
      exporters: [otlphttp/hdx]
