# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
exporters:
  # HTTP setup
  otlphttp/hdx:
    endpoint: 'http://ec2-18-60-50-188.ap-south-2.compute.amazonaws.com:4318'
    tls:
      insecure: true
 
  # gRPC setup (alternative)
  otlp/hdx:
    endpoint: 'ec2-18-60-50-188.ap-south-2.compute.amazonaws.com:4317'
    tls:
      insecure: true
 
service:
  pipelines:
    traces:
      exporters: [spanmetrics, otlphttp/hdx]
    metrics:
      exporters: [otlphttp/hdx]
    logs:
      exporters: [otlphttp/hdx]
