# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file

## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
  exporters:
    otlpgrpc/hyperdx:
      otlp:
        endpoint: peaceful_maxwell:4217
        tls:
          insecure: true
    otlphttp/hyperdx:
      otlp:
        endpoint: http://peaceful_maxwell:4218
        tls:
          insecure: true

  service:
    pipelines:
      traces:
        exporters: [spanmetrics, otlpgrpc/hyperdx]
      metrics:
        exporters: [otlphttp/hyperdx]
      logs:
        exporters: [otlphttp/hyperdx]
