receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}

exporters:
  otlphttp/hdx:
    endpoint: 'http://ec2-18-61-29-74.ap-south-2.compute.amazonaws.com:4318'
    tls:
      insecure: true

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/hdx]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/hdx]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/hdx]
