receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}

exporters:
  otlphttp/hdx:
    endpoint: 'http://ec2-18-61-57-25.ap-south-2.compute.amazonaws.com:4318'
    tls:
      insecure: true
  file:
    path: /var/log/otel-collector/logs.log

service:
  telemetry:
    logs:
      level: debug
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/hdx, file]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/hdx, file]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/hdx, file]
